# Generated by Django 4.2.4 on 2023-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol',
            name='abv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alcohol',
            name='alcoholic',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='alcohol',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='favorite',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='alcoholic',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='drinkThumb',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(default=''),
        ),
    ]
