# Generated by Django 4.2.4 on 2023-08-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_alcohol_abv_alcohol_alcoholic_alcohol_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
