# Generated by Django 4.2.4 on 2023-08-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_rename_instruction_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='type',
            field=models.CharField(default='Others', max_length=100),
        ),
    ]
